# yaml-language-server: $schema=https://www.coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill" # Options: chill, quiet, assertive
  request_changes_workflow: false    # default is false, not sure how intrusive true would be
  
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - ".*"   # reviews for every target branch
