# yaml-language-server: $schema=https://www.coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill" # Options: chill, balanced, assertive
  request_changes_workflow: true
  
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
