name=USBPD_SINK
version=1.0.261006
author=TianpeiLee (WCH)
maintainer=ch32-community
sentence=USBPD_SINK, request 5v, 9v, 12, 15v 20v.
paragraph=CH32 USB Power Delivery (USBPD) library for power negotiation and protocol analysis.
category=Communication
url=https://github.com/ch32-community/arduino_core_ch32 
architectures=ch32v